[package]
name = "musage"
version = "0.0.3"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "🧵 A command line memory usage information tool."
categories = ["command-line-utilities", "filesystem"]
keywords = ["memory",  "ram", "ram-usage"]
repository = "https://github.com/mihaigalos/musage"
license = "MIT"

[dependencies]
autoclap = "0.2.1"
byte-unit = "4.0.13"
clap = "3.0.13"
colored = "2"
procfs = "0.12.0"
