[package]
name = "musage"
version = "0.0.3"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "🧵 A command line memory usage information tool."
categories = ["command-line-utilities", "filesystem"]
keywords = ["memory",  "ram", "ram-usage"]
repository = "https://github.com/mihaigalos/musage"
license = "MIT"

[dependencies]
byte-unit = "4.0.13"
clap = "2.33.2"
colored = "2"
procfs = "0.5.2"
