name: CI
on:
  push:
    paths-ignore:
      - '*.md'
      - 'screenshots/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - '*.md'
      - 'screenshots/**'
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch: # Run with Run Workflow button in the GitHub Action Job, set debug_enabled=true for an interactive ssh session.
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: mihaigalos/config/.github/workflows/rust-ci.yaml@main
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
